---
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "us_pair1"
    instance_type: "t2.micro"
    security_group: default
    region: us-east-1
    aws_secret_key: "{{ec2_secret_key}}" 
    aws_access_key: "{{ec2_access_key}}" 
    network:
      assign_public_ip: true
    image_id: "{{ item.image }}"
    tags:
      environment: "{{item.name}}"
  loop:
    - {image: "ami-04a81a99f5ec58529" , name: "ansible-instance-1"}
    - {image: "ami-04a81a99f5ec58529" , name: "ansible-instance-2"}
    - {image: "ami-0583d8c7a9c35822c" , name: "ansible-instance-3"}



